# Generated by Django 4.2.1 on 2023-05-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classProject', '0002_alter_student_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-first_name'], 'verbose_name': 'The Students', 'verbose_name_plural': 'The Students'},
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
